######################################################################
# Automatically generated by qmake (3.0) Mon Mar 31 13:44:44 2014
######################################################################

TEMPLATE = app
TARGET = window
QT += gui qml quick

SOURCES += main.cpp

RESOURCES += main.qrc

DISTFILES += \
    main.qml \
    Tab1.qml \
    Tab2.qml \
    Tab3.qml \
    NewTab.qml

target.path = $$[QT_INSTALL_EXAMPLES]/qml/platforms/uikit/$$TARGET
INSTALLS += target
