######################################################################
# Automatically generated by qmake (3.0) Mon Mar 31 13:44:44 2014
######################################################################

TEMPLATE = app
TARGET = window

QT += nativecontrols

uikit: QT += nativeuikitcontrols

# Input
SOURCES += main.cpp

target.path = $$[QT_INSTALL_EXAMPLES]/cpp/native/$$TARGET
INSTALLS += target
