######################################################################
# Automatically generated by qmake (3.0) Mon Mar 31 13:44:44 2014
######################################################################

TEMPLATE = app
TARGET = window
QT += gui qml quick
RESOURCES += main.qrc

uikit:!watchos: QTPLUGIN += qnativeuikit

# Input
SOURCES += main.cpp

OTHER_FILES += \
    main.qml

target.path = $$[QT_INSTALL_EXAMPLES]/qml/$$TARGET
INSTALLS += target
