######################################################################
# Automatically generated by qmake (3.0) Mon Mar 31 13:44:44 2014
######################################################################

TEMPLATE = app
TARGET = nativewindow
QT += gui qml quick
RESOURCES += main.qrc

# Input
SOURCES += main.cpp

OTHER_FILES += \
    main.qml

target.path = $$[QT_INSTALL_EXAMPLES]/$$TARGET
INSTALLS += target
