######################################################################
# Automatically generated by qmake (3.0) Mon Mar 31 13:44:44 2014
######################################################################

TEMPLATE = app
QT += gui qml quick
RESOURCES += main.qrc

# Input
SOURCES += main.cpp

OTHER_FILES += \
    main.qml
